### ISSUE TITLE
App fails to load in Safari

### ISSUE THREAD

**Issue by tomoakley** [tobyroworth/Crown-PA-Docs-Site#52]
The app loads in Safari (v11.0.2) but none of the panels are click-able. On render, the console displays these error messages:

- SyntaxError: Cannot use keyword as imported binding name.
- Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) https://crownpa-docs.firebaseapp.com/node_modules/@webcomponents/webcomponentsjs/webcomponents-hi.js

**Comment by tomoakley** [comment]
May took a look at this soon and try to fix it

**Comment by tomoakley** [comment]
https://caniuse.com/#search=web%20components

**Comment by tobyroworth** [comment]
Thanks for your writeup @tomoakley 

_Most of this is a sub-issue of #34_

The 404 is an issue with the build script.

It needs a gulp task modified/added to copy the web components polyfills into the build directory.

Do you have a line reference for that first error?

The screenshot is of the `crown-docs-splash` element, which looks like a styling/enhancement issue #34 - either a lack of grid or a styling error somewhere else. The styling is handled by the index, so the splash displays whilst the components are hydrating. It may then get overridden in the element itself.

The error in your last comment is coming from the `crown-docs-app` element, and looks like there's an issue with the [polymer properties ](https://www.polymer-project.org/2.0/docs/devguide/properties). There is a long-standing race condition there though, so that might be part of a known problem I never bugged.
